//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PD218.rc
//
#define IDD_PD218_DIALOG                102
#define IDD_password                    105
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_PD218                       133
#define IDD_CFJ_EDITOR                  134
#define IDD_RegCode                     134
#define IDD_MCFJ_DEAL                   135
#define IDD_NEWPASSWORD                 136
#define IDD_SelDutCom                   137
#define IDD_SelDir                      138
#define IDD_NEWDATE                     139
#define IDD_SetPar                      140
#define IDD_AudioScale                  142
#define IDD_RFPWR_LOSS                  143
#define IDD_LED_ADJUST                  145
#define IDD_SETTING                     147
#define IDC_EPassword                   1001
#define IDC_enterPassword               1002
#define IDC_STATIC2                     1003
#define IDC_STATIC3                     1004
#define IDC_TxPowerSel                  1013
#define IDC_Tx_WriteUid                 1015
#define IDC_Charge_Adjust               1016
#define IDC_Tx_WriteUid2                1016
#define IDC_Tx_WriteUid_Auto            1016
#define IDC_Verify_Def_Addr             1017
#define IDC_io_check                    1023
#define IDC_BMODLE_SEL                  1024
#define IDC_TxVersionSel                1025
#define IDC_BMODLE_CURRENT              1026
#define IDC_PWR_ON_CUR                  1026
#define IDC_TxCurentMin                 1027
#define IDC_MIC_SPK                     1028
#define IDC_MBAIS                       1029
#define IDC_PWR_OFF_CUR                 1030
#define IDC_Read_BT_Name                1031
#define IDC_PIO_00_Chk                  1032
#define IDC_TxPwrMin                    1033
#define IDC_ESpecAnalyPort              1034
#define IDC_TxSencitive                 1035
#define IDC_PIO_01_Chk                  1036
#define IDC_PIO_02_Chk                  1037
#define IDC_PIO_03_Chk                  1038
#define IDC_PIO_04_Chk                  1039
#define IDC_PIO_05_Chk                  1040
#define IDC_PIO_06_Chk                  1041
#define IDC_LIST1                       1042
#define IDC_PIO_07_Chk                  1042
#define IDC_Start                       1043
#define IDC_PIO_08_Chk                  1043
#define IDC_CurTestItem                 1044
#define IDC_PIO_09_Chk                  1044
#define IDC_CurTestObj                  1045
#define IDC_PIO_10_Chk                  1045
#define IDC_CurTestItem2                1046
#define IDC_PIO_11_Chk                  1046
#define IDC_CurTestObj2                 1047
#define IDC_PIO_12_Chk                  1047
#define IDC_LIST2                       1048
#define IDC_PIO_13_Chk                  1048
#define IDC_PIO_14_Chk                  1049
#define IDC_PIO_15_Chk                  1050
#define IDC_PIO_19_Chk                  1051
#define IDC_Audio_pio_pass              1052
#define IDC_PIO_20_Chk                  1052
#define IDC_Audio_pio_fail              1053
#define IDC_PIO_29_Chk                  1053
#define IDC_PIO_30_Chk                  1054
#define IDC_TxCurrentMax                1055
#define IDC_enterRegisterCode           1056
#define IDC_PIO_31_Chk                  1056
#define IDC_EAddress                    1057
#define IDC_PIO_17_Chk                  1057
#define IDC_MBIAS_B_Chk                 1058
#define IDC_RICHEDIT1                   1059
#define IDC_read_addr                   1059
#define IDC_WRITE_FILE                  1060
#define IDC_AIO_Chk                     1061
#define IDC_KEEP_CSPAR                  1061
#define IDC_MBIAS_A_Chk                 1062
#define IDC_reset_finish                1068
#define IDC_N4010A_TEST                 1069
#define IDC_OUTPUT_CFJ                  1072
#define IDC_INPUT_CFJ                   1073
#define IDC_Tx_Xtal_Adj                 1075
#define IDC_OLDPASSWORD                 1075
#define IDC_NEWPASSWORD                 1076
#define IDC_BUTTON1                     1077
#define IDC_CONFIRM                     1077
#define IDC_AUTO_RUN                    1077
#define IDC_DO_PWRCAL                   1077
#define IDC_LED_CAL_BTN                 1077
#define IDC_STATIC1                     1078
#define IDC_year                        1087
#define IDC_month                       1088
#define IDC_day                         1089
#define IDC_SELCOM_PROMPT               1119
#define IDC_Multimeter                  1120
#define IDC_COMBO_A                     1125
#define IDC_COMBO_AG                    1126
#define IDC_RADIO_A                     1127
#define IDC_RADIO_AG                    1128
#define IDC_TEST_NUMA                   1128
#define IDC_RADIO_B                     1129
#define IDC_TEST_NUMB                   1129
#define IDC_RADIO_BG                    1130
#define IDC_CSEL_ORDER_NUM              1130
#define IDC_COMBO_B                     1131
#define IDC_COMBO_ORDER                 1131
#define IDC_COMBO_BG                    1132
#define IDC_COMBO_WK_NUM                1132
#define IDC_CUR_ADDR                    1133
#define IDC_END_ADDR                    1134
#define IDC_DEF_ADDR                    1135
#define IDC_SBT_ADDR                    1136
#define IDC_SEND_ADDR                   1137
#define IDC_SDEF_ADDR                   1138
#define IDC_PC_AD_MIN                   1139
#define IDC_SPC_AD_MIN                  1140
#define IDC_PC_THD                      1141
#define IDC_SPC_THD                     1142
#define IDC_SMIC_ROUTING                1143
#define IDC_MIC_ROUTING                 1145
#define IDC_SSPK_ROUTING                1146
#define IDC_SPK_ROUTING                 1148
#define IDC_SARF_LOSS                   1149
#define IDC_ARF_LOSS                    1150
#define IDC_SBRF_LOSS                   1151
#define IDC_BRF_LOSS                    1152
#define IDC_WFILE                       1153
#define IDC_WFILE_CRC32                 1154
#define IDC_SAVE_ADDR_FREQ              1155
#define IDC_SAVE_FREQ                   1156
#define IDC_SG_SEL                      1157
#define IDC_SEL_GOLDEN                  1158
#define IDC_SG_CURRENT_MIN              1159
#define IDC_G_current_min               1160
#define IDC_SG_CURRENT_MAX              1161
#define IDC_G_current_max               1162
#define IDC_SG_ADDR                     1163
#define IDC_G_ADDR                      1164
#define IDC_SG_NAME                     1165
#define IDC_G_NAME                      1166
#define IDC_SG_VER                      1167
#define IDC_G_VER                       1168
#define IDC_SG_AUDIO_TH                 1169
#define IDC_SG_AUDIO_LV                 1170
#define IDC_G_audio_thd                 1171
#define IDC_G_audio_lv                  1172
#define IDC_G_audio_lv_min              1173
#define IDC_SG_AUDIO_LV_MIN             1174
#define IDC_SG_AUDIO_LV_MAX             1175
#define IDC_G_audio_lv_max              1176
#define IDC_SG_RF_PWR_MIN               1177
#define IDC_G_RF_PWR_MIN                1178
#define IDC_SG_RF_PWR_MAX               1179
#define IDC_G_RF_PWR_MAX                1180
#define IDC_SG_RF_PWR_PEAK              1181
#define IDC_G_RF_PWR_PEAK               1182
#define IDC_SG_SENS                     1183
#define IDC_G_SENS                      1184
#define IDC_SG_NEG_FOFFSET              1185
#define IDC_SG_FOFFSET                  1185
#define IDC_G_NEG_FOFFSET               1186
#define IDC_G_FOFFSET                   1186
#define IDC_ARF_LOSSM                   1187
#define IDC_SG_POS_FOFFSET              1188
#define IDC_SG_EXP_POWER                1188
#define IDC_G_POS_FOFFSET               1189
#define IDC_G_EXP_POWER                 1189
#define IDC_PROMPT                      1190
#define IDC_ARF_LOSSH                   1190
#define IDC_AG_VAmplitude               1191
#define IDC_BRF_LOSSM                   1191
#define IDC_BG_VAmplitude               1192
#define IDC_BRF_LOSSH                   1192
#define IDC_AG_Amplitude                1193
#define IDC_SG_RF_PWR_CENTER            1193
#define IDC_BG_Amplitude                1194
#define IDC_G_RF_PWR_CENL               1194
#define IDC_G_RF_AVPWR_L                1194
#define IDC_ADEV_ADDRESS                1195
#define IDC_BDEV_ADDRESS                1196
#define IDC_SBDEV_ADDRESS               1197
#define IDC_G_RF_PWR_MIN2               1198
#define IDC_MultimeterVal               1199
#define IDC_G_RF_PWR_MAX2               1199
#define IDC_DEF_XTAL_PAR                1200
#define IDC_SDEF_XTAL_PAR               1201
#define IDC_XTAL_MIN                    1202
#define IDC_XTAL_MAX                    1203
#define IDC_PROMPT2                     1203
#define IDC_XTAL_GOFFSET                1204
#define IDC_ARF_PWR                     1204
#define IDC_SDEF_POWER_PAR              1204
#define IDC_G_RF_PWR_CENM               1205
#define IDC_BRF_PWR                     1205
#define IDC_G_RF_AVPWR_M                1205
#define IDC_G_RF_PWR_MIN3               1206
#define IDC_DEF_POWER_PAR               1206
#define IDC_G_RF_PWR_MAX3               1207
#define IDC_POWER_MIN                   1207
#define IDC_G_RF_PWR_CENH               1208
#define IDC_G_RF_AVPWR_H                1208
#define IDC_ARF_FLOSSH                  1209
#define IDC_XTAL_BGOFFSET               1210
#define IDC_PWR_STEP1                   1210
#define IDC_POWER_MAX                   1210
#define IDC_PWR_STEP2                   1211
#define IDC_DUT1_UART_PORT              1211
#define IDC_PWR_STEP3                   1212
#define IDC_DUT1_UART_RATE              1212
#define IDC_PWR_STEP4                   1213
#define IDC_DUT2_UART_PORT              1213
#define IDC_PWR_STEP5                   1214
#define IDC_DUT2_UART_RATE              1214
#define IDC_PWR_STEP6                   1215
#define IDC_PWR_STEP7                   1216
#define IDC_SG_SENS2                    1216
#define IDC_PWR_STEP8                   1217
#define IDC_DUT_SENSPOWER               1217
#define IDC_PWR_MIN                     1218
#define IDC_SG_FOFFSET2                 1218
#define IDC_PWR_MAX                     1219
#define IDC_PWROFF_CUR_MIN              1219
#define IDC_DUT_FOFFSET                 1219
#define IDC_PWR_ADJ_MIN                 1220
#define IDC_PWROFF_CUR_MAX              1220
#define IDC_SG_EXP_POWER2               1220
#define IDC_PWR_ADJ_MAX                 1221
#define IDC_PWRON_CUR_MIN               1221
#define IDC_LANGUAGE_SELECT             1222
#define IDC_PWRON_CUR_MAX               1222
#define IDC_CONTINUE_RUN                1223
#define IDC_DUT_INPUTPOWER              1223
#define IDC_LF_PW_CHK                   1224
#define IDC_S_AVPOWERMIN                1224
#define IDC_MF_PW_CHK                   1225
#define IDC_DUT_AVPOWERMIN              1225
#define IDC_HF_PW_CHK                   1226
#define IDC_S_AVPOWERMAX                1226
#define IDC_LF_IC_CHK                   1227
#define IDC_DUT_AVPOWERMAX              1227
#define IDC_MF_IC_CHK                   1228
#define IDC_S_SENSPACKETS               1228
#define IDC_HF_IC_CHK                   1229
#define IDC_DUT_SENSPACKETS             1229
#define IDC_LF_SS_CHK                   1230
#define IDC_MF_SS_CHK                   1231
#define IDC_HF_SS_CHK                   1232
#define IDC_U45_SNR_CHK                 1233
#define IDC_U51_SNR_CHK                 1234
#define IDC_U56_SNR_CHK                 1235
#define IDC_MTOR_1_CHK                  1236
#define IDC_MTOR_3_CHK                  1237
#define IDC_MTOR_5_CHK                  1238
#define IDC_U49_SNR_CHK                 1239
#define IDC_U55_SNR_CHK                 1240
#define IDC_U60_SNR_CHK                 1241
#define IDC_MTOR_2_CHK                  1242
#define IDC_MTOR_4_CHK                  1243
#define IDC_MTOR_6_CHK                  1244
#define IDC_METHOD_LED_CHK              1245
#define IDC_USE_TBOX                    1246
#define IDC_PSKEY_WRITE_CHK             1247
#define IDC_CVC_WRITE_CHK               1248
#define IDC_AUDIO_AMP_CHK               1249
#define IDC_SPI_LOCK_CHK                1250
#define IDC_A_LED                       1253
#define IDC_B_LED                       1254
#define IDC_UNLOCK_CHK                  1255
#define IDC_COMBO_SNR_SEL               1259
#define IDC_LED0_RED_ADC_MIN            1260
#define IDC_LED0_GREEN_ADC_MIN          1261
#define IDC_LED0_RED_ADC_ADJ            1262
#define IDC_LED0_BLUE_ADC_MIN           1263
#define IDC_LED0_GREEN_ADC_ADJ          1264
#define IDC_LED0_BLUE_ADC_ADJ           1265
#define IDC_LED0_RED_OFFSET             1266
#define IDC_LED1_RED_ADC_MIN            1267
#define IDC_LED1_GREEN_ADC_MIN          1268
#define IDC_LED1_BLUE_ADC_MIN           1269
#define IDC_LED1_RED_ADC_ADJ            1270
#define IDC_LED1_GREEN_ADC_ADJ          1271
#define IDC_LED1_BLUE_ADC_ADJ           1272
#define IDC_LED1_RED_OFFSET             1273
#define IDC_LED0_GREEN_OFFSET           1274
#define IDC_COMBO_DUT_AUDIO_MODE        1275
#define IDC_LED0_BLUE_OFFSET            1276
#define IDC_USE_KEY_CHK                 1276
#define IDC_LED1_GREEN_OFFSET           1277
#define IDC_LED1_BLUE_OFFSET            1278
#define IDC_LED0_RED_ADC_Max            1279
#define IDC_LED0_GREEN_ADC_Max          1280
#define IDC_LED0_BLUE_ADC_Max           1281
#define IDC_LED1_RED_ADC_Max            1282
#define IDC_LED1_GREEN_ADC_Max          1283
#define IDC_LED1_BLUE_ADC_Max           1284
#define IDC_FCOUNTER_OFFSET             1285
#define IDC_UART_LOOPBACK               1286
#define IDC_SEL_PROJECT                 1287
#define IDC_BurnSoftware                1288
#define IDC_PWR_CUR                     1289
#define IDC_PIO_CHK                     1290
#define IDC_ADC_CHK                     1291
#define IDC_WRITE_MAC                   1292
#define IDC_AUTO_W_MAC                  1293
#define IDC_FREQUENCY_TEST              1294
#define IDC_POWER_TEST                  1295
#define IDC_SEND_TEST                   1296
#define IDC_RECV_TEST                   1297
#define IDC_SHOW_MAC                    1298
#define IDC_MCU_IO_CHK                  1299
#define IDC_8711_IO_CHK                 1300
#define IDC_READ_SOFT_VER               1301
#define IDC_LF_EVM_CHK                  1302
#define IDC_MF_EVM_CHK                  1303
#define IDC_HF_EVM_CHK                  1304
#define IDC_EVM_MAX                     1306
#define IDC_SENS_ERR_PER_MAX            1307
#define IDC_BW20_BW40_DF                1308
#define IDC_B_EVM_LOSS                  1309
#define IDC_A_EVM_LOSS                  1310
#define IDC_A_EVM_LOSSM                 1311
#define IDC_A_EVM_LOSSH                 1312
#define IDC_B_EVM_LOSSM                 1313
#define IDC_B_EVM_LOSSH                 1314
#define IDC_A_SENS_LOSS                 1315
#define IDC_B_SENS_LOSS                 1316
#define IDC_A_SENS_LOSSM                1317
#define IDC_A_SENS_LOSSH                1318
#define IDC_B_SENS_LOSSM                1319
#define IDC_B_SENS_LOSSH                1320
#define IDC_G_EXP_EVM                   1325
#define IDC_G_EXP_EVM_L                 1326
#define IDC_G_EXP_EVM_M                 1327
#define IDC_G_EXP_EVM_H                 1328
#define IDC_OFDM_BW40_DF                1329
#define IDC_INSTRUMENT_COMPENSATE       1330
#define IDC_SET_SOFT_VER                1331
#define IDC_AGOLD_ADDR                  1332
#define IDC_BGOLD_ADDR                  1333
#define ID_MMCurConfig                  32771
#define ID_CN_TOOL_DEV                  32782
#define ID_MCFG_DLG                     32783
#define ID_MSEL_TITEM                   32784
#define ID_CN_Multimeter                32785
#define ID_MAUTHORITY                   32786
#define ID_CFG_AUDIO_ROUT               32787
#define ID_CN_IOCARD                    32788
#define ID_MENUITEM32789                32789
#define ID_MPAR_PASSWORD                32790
#define ID_MTITEM_PASSWORD              32791
#define ID_MCFG_PASSWORD                32792
#define ID_MDATE_PASSWORD               32793
#define ID_MAUTHORITY_PASSWORD          32794
#define ID_MSET_DATE                    32795
#define ID_CN_AMODLE                    32796
#define ID_CN_BMODLE                    32797
#define ID_CN_TBOX                      32798
#define ID_EXIT_DIALOG                  32799
#define ID_CLR_TCOUNT                   32800
#define ID_RFPWR_LOSS_ADJ               32801
#define ID_CN_FCounter                  32803
#define ID_lLED_ADC_CAL                 32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1334
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
